[package]
name = "memprof"
version = "0.1.0"
authors = ["Jean-Baptiste Skutnik <jb.skutnik@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "*"
signal-hook = "*"
